config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  resources :rooms, only: [:show, :create] do
    resources :musics, only: [:new, :create, :destroy]
    resources :users, only: [:create]
  end

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :musics, only: [:show], param: :url
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/music.rb
class Music < ApplicationRecord
  belongs_to :room
  belongs_to :user

  validates :url, presence: true, uniqueness: true
  validates :title, presence: true
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :users
  has_many :musics

  validates :name, presence: true, uniqueness: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :musics
  belongs_to :room

  validates :name, presence: true, uniqueness: true
end

app/controllers/api/v1/base_controller.rb
class Api::V1::BaseController < ActionController::API
  before_action :set_cors_header

  def set_cors_header
    response.headers['Access-Control-Allow-Origin'] = '*'
  end
end

app/controllers/api/v1/musics_controller.rb
class Api::V1::MusicsController < Api::V1::BaseController
  before_action :find_music, only: [:show]

  def show
  end

  private

  def find_music
    @music = Music.find_by(url: params[:url])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/musics_controller.rb
class MusicsController < ApplicationController
  skip_before_action :verify_authenticity_token
  before_action :find_room, only: [:new, :create, :destroy]

  def new
    @musics = Music.where(room_id: @room)
  end

  def create
    @music = Music.new(music_params)
    user_name = session[:user_name] # Use cookies to get the username
    user_id = User.where(name: user_name)[0].id
    @music.user_id = user_id
    if @music.save
      RoomChannel.broadcast_to(@room, render_to_string(partial: 'video', locals: { music: @music }))
    end
    @last_music = Music.last
  end

  def destroy
    @music = Music.find(params[:id])
    @music.destroy
  end

  private

  def music_params
    params.require(:music).permit(:url, :title, :room_id)
  end

  def find_room
    @room = Room.find(params[:room_id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @room = Room.new
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :find_room, only: [:show]

  def show
    @musics = Music.where(room_id: @room.id)
    @users = User.where(room_id: @room.id)
    @first_music = Music.where(room_id: @room.id).first
  end

  def create
    @create = Room.new(room_params)
    @create.save!
    # new_room = CreateRoom.call
    redirect_to new_room_music_path(@create)
  end

  private

  def room_params
    params.require(:room).permit(:name)
  end

  def find_room
    @room = Room.find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :verify_authenticity_token

  def create
    @user = User.new(user_params)
    @user.save!
    session[:user_name] = @user.name
  end

  def destroy
  end

  private

  def user_params
    params.require(:user).permit(:name, :room_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/musics_helper.rb
module MusicsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Jukebox</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= stylesheet_pack_tag 'application', media: 'all' %>
  </head>

  <body>
    <%= yield %>
    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/musics/_video.html.erb
<li id="next-music" data-id="<%= music.id %>" data-videoid="<%= music.url %>">
  <p class="playlist-card py-3 px-4 border-b border-gray-400 text-orange-200"><%= music.title %></p>
</li>

app/views/musics/create.html.erb
<h1 id="id"><%= @last_music.title %></h1>

app/views/musics/new.html.erb
<!-- grid container -->
<div class="grid grid-cols-1 gap-4 h-screen">
  <!-- Room name block -->
  <div class="text-center col-span-1">
    <h1 id="room-infos" class="text-4xl text-orange-200" data-roomid="<%= @room.id %>"><%= @room.name %></h1>
  </div>
  <!-- nickname block -->
  <div class="flex justify-center col-span-1">
    <form id="nickname-form" class=" nickname-form flex items-center border-b border-b-2 border-teal-500 py-2 w-1/2">
      <input id="name-form" class="text-orange-200 appearance-none bg-transparent border-none w-full text-gray-700 mr-3 py-1 px-2 leading-tight focus:outline-none" type="text" placeholder="Entres ton nom" aria-label="nickname">
      <input type="submit" id="name-button" value="Envoyer" class="flex-shrink-0 bg-teal-500 hover:bg-teal-700 border-teal-500 hover:border-teal-700 text-sm border-4 text-white py-1 px-2 rounded">
    </form>
  </div>
  <!-- music search block -->
  <div class="flex justify-center col-span-1">
    <form id="search-form" class="search-form flex items-center border-b border-b-2 border-teal-500 py-2 w-1/2">
      <input id="form" class="text-orange-200 appearance-none bg-transparent border-none w-full text-gray-700 mr-3 py-1 px-2 leading-tight focus:outline-none" type="text" placeholder="Cherches une musique sur YouTube" aria-label="nickname">
      <input type="submit" value="Search" class="flex-shrink-0 bg-teal-500 hover:bg-teal-700 border-teal-500 hover:border-teal-700 text-sm border-4 text-white py-1 px-2 rounded">
    </form>
  </div>
  <div class="flex justify-center col-span-1"><%= link_to "Aller vers la party room", room_path(@room) %></div>
  <!-- results block -->
  <ul id="results"></ul>

  <!-- music list div -->
  <div class="col-span-1 flex justify-center overflow-scroll h-full">
    <ul id="videos-container">
    <% @musics.each do |music| %>
      <%= render 'musics/video', music: music %>
    <% end %>
    </ul>
  </div>
</div>

app/views/pages/home.html.erb
<!-- grid container -->
<div class="grid grid-cols-1 gap-4">
  <h1 class="col-span-1 text-3xl text-center text-orange-200">Jukebox</h1>
  <div class="col-span-1 text-center">
    <p class="h-full flex justify-center items-center text-orange-200">Playlist commune pendant le confinement</p>
  </div>
  <!-- form container -->
  <div class="flex justify-center col-span-1">
    <div class="w-1/2">
    <%= form_for (@room), method: :post do |f| %>
      <div class="flex items-center border-b border-b-2 border-teal-500 py-2">
        <%= f.text_field :name, placeholder: "Entrez le nom de votre soirée", class: "text-orange-200 appearance-none bg-transparent border-none w-full text-gray-700 mr-3 py-1 px-2 leading-tight focus:outline-none" %>
        <%= f.submit "Let's Go !", class: "flex-shrink-0 bg-teal-500 hover:bg-teal-700 border-teal-500 hover:border-teal-700 text-sm border-4 text-white py-1 px-2 rounded" %>
      </div>
    <% end %>
    </div>
  </div>
</div>

app/views/rooms/index.html.erb
<h1>Rooms#index</h1>
<p>Find me in app/views/rooms/index.html.erb</p>

app/views/rooms/show.html.erb
<!-- grid container -->
<div class="grid grid-cols-1 gap-4">
  <!-- Room name block -->
  <div class="text-center col-span-1">
    <h1 id="room-infos" class="text-4xl text-orange-200" data-roomid="<%= @room.id %>"><%= @room.name %></h1>
    <h3 class="text-orange-200">Bienvenue <%= session[:user_name] %></h3>
  </div>
  <!-- search bar block -->
  <div class="flex justify-center col-span-1">
    <form id="search-form" class="search-form flex items-center border-b border-b-2 border-teal-500 py-2 w-1/2">
      <input id="form" class="appearance-none text-orange-200 bg-transparent border-none w-full text-gray-700 mr-3 py-1 px-2 leading-tight focus:outline-none" type="text" placeholder="Cherches une musique sur YouTube" aria-label="Video">
      <input type="submit" value="Search" class="flex-shrink-0 bg-teal-500 hover:bg-teal-700 border-teal-500 hover:border-teal-700 text-sm border-4 text-white py-1 px-2 rounded">
    </form>
  </div>
  <!-- results block -->
  <ul id="results"></ul>

  <!-- player div from the youtube API doc -->
  <div class="col-span-1 flex justify-center">
  <div id="player"></div>
  </div>
  <script>
      // 2. This code loads the IFrame Player API code asynchronously.
      var firstMusic = "<%= @first_music.url %>"
      var tag = document.createElement('script');

      tag.src = "https://www.youtube.com/iframe_api";
      var firstScriptTag = document.getElementsByTagName('script')[0];
      firstScriptTag.parentNode.insertBefore(tag, firstScriptTag);

      // 3. This function creates an <iframe> (and YouTube player)
      //    after the API code downloads.
      var videoId = null;
      var player;
      function onYouTubeIframeAPIReady() {
        player = new YT.Player('player', {
          height: '360',
          width: '640',
          videoId: firstMusic,
          events: {
            // 'onReady': onPlayerReady,
            'onStateChange': onPlayerStateChange
          }
        });
      }

      // 4. The API will call this function when the video player is ready.
      function onPlayerReady(event) {
        event.target.playVideo();
      }

      // 5. The API calls this function when the player's state changes.
      //    The function indicates that when playing a video (state=1),
      //    the player should play for six seconds and then stop.
      var done = false;
      function onPlayerStateChange(event) {
        if (event.data === 0) {
          const musicToDelete = document.querySelector('#next-music');
          deleteMusic(musicToDelete);
          musicToDelete.remove();
          videoId = document.querySelector('#next-music').dataset.videoid;
          console.log(videoId);
          event.target.loadVideoById(`${videoId}`);
          // onYouTubeIframeAPIReady();
        }
      }
      function stopVideo() {
        player.stopVideo();
      }

      const deleteMusic = (musicToDelete) => {
        const idToDelete = musicToDelete.dataset.id;
        const deleteParams = location.href;
        fetch(`${deleteParams}/musics/${idToDelete}`, {
          method: 'DELETE'
        })
        .catch(error => {
          console.log(error);
        });
      }
    </script>
  <!-- music playlist div -->
  <div class="col-span-1 flex justify-center overflow-scroll h-64">
    <ul id="videos-container">
      <h4 class="text-orange-200 text-3xl">A suivre...</h4>
    <% @musics.each do |music| %>
      <%= render 'musics/video', music: music %>
    <% end %>
    </ul>
  </div>
</div>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/destroy.html.erb
<h1>Users#destroy</h1>
<p>Find me in app/views/users/destroy.html.erb</p>